[project]
name = "mlscript_interpreter"
version = "0.8.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["interpreter","mlscript_kernel"]