name: Build and Publish Wheels

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # This is the new debugging step.
      - name: "DEBUG: List files and check .gitmodules"
        run: |
          echo "--- Listing all files recursively ---"
          Get-ChildItem -Recurse
          echo "--- Contents of .gitmodules ---"
          Get-Content .gitmodules
        shell: pwsh

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v2.19
        env:
          CIBW_SKIP: "cp36-* cp37-*"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_TEST_COMMAND: "python main.py test_suite.ms"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
  
  publish_to_pypi:
    name: Publish wheels to PyPI
    needs: [build_wheels]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: wheelhouse
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0